# Generated by Django 4.2.4 on 2023-08-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0002_avatar_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
